In [68]:
from nltk.corpus import brown
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
import numpy as np
import nltk

In [ ]:
nltk.download()

In [3]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [4]:
reviews = brown.sents(categories='reviews')

In [5]:
print(len(brown.words(categories='reviews')))

40704


In [6]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [7]:
text = "It was a pleasant day, I went to the market to buy some fruits..."

In [8]:
print(word_tokenize(text))

['It', 'was', 'a', 'pleasant', 'day', ',', 'I', 'went', 'to', 'the', 'market', 'to', 'buy', 'some', 'fruits', '...']


In [9]:
sent_text = "Cat is running. I play football. I love python"

In [10]:
sent_tokenize(sent_text)

['Cat is running.', 'I play football.', 'I love python']

In [11]:
# Stop words

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\piyus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
sw = set(stopwords.words('english'))
stopwords

<WordListCorpusReader in 'C:\\Users\\piyus\\AppData\\Roaming\\nltk_data\\corpora\\stopwords'>

In [14]:
from nltk.stem import PorterStemmer, LancasterStemmer, SnowballStemmer

In [15]:
ps = PorterStemmer()

In [16]:
ps.stem("jumping")

'jump'

In [17]:
ps.stem('jumped')

'jump'

In [18]:
ps.stem("awesome")

'awesom'

In [19]:
ps.stem('jivitesh')

'jivitesh'

In [26]:
def clean(sentence):
    sentence = tokenizer.tokenize(sentence)
    return [ps.stem(w) for w in sentence if w not in sw]

In [27]:
text = "i like to play with my friends all, the time and i am not ashamed to admit that fellas"
print(text)

i like to play with my friends all, the time and i am not ashamed to admit that fellas


In [28]:
print(clean(text))

['like', 'play', 'friend', 'time', 'asham', 'admit', 'fella']


In [25]:
tokenizer = RegexpTokenizer("[a-zA-Z]+")

### 3. Building common vocubulary

In [53]:
corpus = ["Indian cricket team will win World Cup",
         "We will win next Lok Sabha Election, says Indian PM",
         "Raazi is an exciting Indian spy movie based on real incident",
         "APJ Won hearts of many Indians."]

In [54]:
new_corpus = []
for sen in corpus:
    sentence = tokenizer.tokenize(sen)
    sentence = " ".join(sentence)
    corpus = [ps.stem(w) for w in sentence if w not in sw]
    new_corpus.append(sentence)

In [55]:
new_corpus

['Indian cricket team will win World Cup',
 'We will win next Lok Sabha Election says Indian PM',
 'Raazi is an exciting Indian spy movie based on real incident',
 'APJ Won hearts of many Indians']

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
cv = CountVectorizer()

In [58]:
cv.fit_transform(new_corpus)

<4x30 sparse matrix of type '<class 'numpy.int64'>'
	with 34 stored elements in Compressed Sparse Row format>

In [72]:
vectorised_corpus = cv.fit_transform(new_corpus).toarray()
print(vectorised_corpus)

[[0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0]
 [1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]]


In [73]:
vectorised_corpus.shape

(4, 30)

In [79]:
new_text = np.ones((22,))

In [80]:
new_text[3:7]=0
print(cv.inverse_transform(new_text))

[array(['an', 'apj', 'based', 'hearts', 'incident', 'indian', 'indians',
       'is', 'lok', 'many', 'movie', 'next', 'of', 'on', 'pm', 'raazi',
       'real', 'sabha'], dtype='<U8')]


In [84]:
cv.vocabulary_

{'indian': 9,
 'cricket': 3,
 'team': 24,
 'will': 26,
 'win': 27,
 'world': 29,
 'cup': 4,
 'we': 25,
 'next': 15,
 'lok': 12,
 'sabha': 21,
 'election': 5,
 'says': 22,
 'pm': 18,
 'raazi': 19,
 'is': 11,
 'an': 0,
 'exciting': 6,
 'spy': 23,
 'movie': 14,
 'based': 2,
 'on': 17,
 'real': 20,
 'incident': 8,
 'apj': 1,
 'won': 28,
 'hearts': 7,
 'of': 16,
 'many': 13,
 'indians': 10}