In [2]:
import numpy as np

In [ ]:
# Above - Esc, A
# below - Esc, B
#Markdown - Esc, M
#Code - Esc, Y
# delete - esc, DD
#undo - esc, z

In [4]:
l = [1,2,3]
a = np.array(l)
print(a)
print(type(a))
print(l)
print(type(l))

[1 2 3]
<class 'numpy.ndarray'>
[1, 2, 3]
<class 'list'>


In [5]:
a.shape

(3,)

In [12]:
a+1

array([2, 3, 4])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr.shape

(2, 3)

In [36]:
z = np.zeros((1,5), dtype = int)
print(type(z[0,1]))
z

<class 'numpy.int32'>


array([[0, 0, 0, 0, 0]])

# Random number generator

In [49]:
x = np.random.randint(10,20,5)
x

array([16, 16, 12, 10, 13])

In [50]:
type(x)

numpy.ndarray